name: Check manga RSS

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit do state.json se houver alteração
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet; then
            echo "Nenhuma alteração para commit."
          else
            git add state.json
            git commit -m "Atualiza estado do último capítulo"
            git push
          fi